### ISSUE TITLE
TaggablePool and Pool overrides prefix_key and prefix_tag options with hardcoded values

### ISSUE THREAD

**Issue by alexpica** [frqnck/apix-cache#13]
Hello,

I am looking at an issue when creating a pool using a factory, if I set the 'prefix_key' and 'prefix_tag' options they are overriden with hardcoded values: 'apix-key-' and 'apix-tag-'. 

Apparently this happens in the constructors of TaggablePool and Pool. I would suggest to pass maybe just the 'taggable' boolean attribute to the adapters, and maybe not include the prefixes :)

Regards,
Alex

**Comment by frqnck** [comment]
Hi @alexpica 

Well spotted. The extreanous prefixes did not bring much...
Fixed in master + the relevant regression tests. 

Many thanks,
Franck
