### ISSUE TITLE
Files cache not correctly handling EOL on Windows

### ISSUE THREAD

**Issue by davybatsalle** [frqnck/apix-cache#15]
Hello,

Whenever I try to read a cache file generated through Files on Windows, I get a miss with the following PHP notice:
PHP Notice:  unserialize(): Error at offset 0 of 3224505 bytes in D:\....\vendor\apix\cache\src\Files.php on line 70

I realized that Files::loadKey relies on the assumption that PHP_EOL (used for adding key and expiration to the cache entry) is of size 1, which is not the case on Windows (\r\n).
Just to check that it was indeed the issue, I changed 2 lines in Files::loadKey to have:
$pos+strlen(PHP_EOL)
instead of:
$pos+1

and the unserialize function returned correctly this time.
I'm not sure this is the only occurence of the issue.

Could it be possible to have a fix for this?

Best regards,

--
Davy

**Comment by frqnck** [comment]
Hi @davybatsalle, thanks for pointing this out. Your fix make sense.

Could you submit a PR?

Do you see that specific issue when running `phpunit tests/FilesTest.php`?
If not, could you also add a test that does.

**Comment by frqnck** [comment]
Fixed in PR https://github.com/frqnck/apix-cache/pull/16.
