### ISSUE TITLE
Use of Redis KEYS command is discouraged

### ISSUE THREAD

**Issue by jspalink** [frqnck/apix-cache#18]
From [Redis Documentation](http://redis.io/commands/KEYS):
> Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.

The Redis module probably shouldn't be using the keys command - could probably be replaced with a private function that runs a scan on a pattern and compiles those lists.

**Comment by frqnck** [comment]
Hi @jspalink. Thanks for the info. Feel free to PR any alternative.

`\Redis::keys()` is only used within the `Apix\Redis::flush()` method -- which is rarely used. The use of this method is generally for very special operation (maintenance), one that you should not use in production.
